### ISSUE TITLE
verification error in xh_ssteptrace

### ISSUE THREAD

**Issue by zpzigi** [hypcode/uberspark#1]
if I type "make verify" command in uberspark/uxmhf/xmhf-uobjs/xh_ssteptrace
it brings out the following error.

cp				 -f /home/changho/uberspark/uxmhf/_objects/_verif_bp/xh_ssteptrace_sstub.ag.v.c _verif_xh_ssteptrace/.
cp: cannot stat ‘/home/changho/uberspark/uxmhf/_objects/_verif_bp/xh_ssteptrace_sstub.ag.v.c’: No such file or directory

This prevents 'make uxmhf-verifyuobjs-all' from being succeeded.

The same error also happens when I type "make verify" in uberspark/uxmhf/xmhf-uobjs/xg_richguest

cp				 -f /home/changho/uberspark/uxmhf/_objects/_verif_bp/xg_richguest_sstub.ag.v.c _verif_xg_richguest/.
cp: cannot stat ‘/home/changho/uberspark/uxmhf/_objects/_verif_bp/xg_richguest_sstub.ag.v.c’: No such file or directory

The command seems to work well for other uber objects.
Could you check this error please?

**Comment by amitvasudevan** [comment]
xg_richguest and xh_ssteptrace are written as examples of "unverified" uber objects and therefore do not have a verification harness

**Comment by zpzigi** [comment]
Thank you for your response.
Why then is ssteptrace included in uxmhf-verifyuobjs-all so that it does
not work?
'make uxmhf-verifyuobjs-all' is stuck by xh_ssteptrace.
I think this error should be fixed.

Regards,

2017. 7. 18. 오전 1:17에 "Amit Vasudevan" <notifications@github.com>님이 작성:

**Comment by amitvasudevan** [comment]
Indeed. I am re-opening the issue and will make a fix soon. 
Thanks!

**Comment by hypcode** [comment]
Fixed. Grab from master.

https://github.com/hypcode/uberspark/commit/04e6716119b8a1413b5205b302ea55e8465b0384
